services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: &web_build
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/docker_practice
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
  tailwind:
    build:
      <<: *web_build
    command: bin/rails tailwindcss:watch
    tty: true
    volumes:
      - .:/docker_practice
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
      - "./redis.conf:/opt/homebrew/etc/redis.conf"
    command: redis-server /opt/homebrew/etc/redis.conf
  sidekiq:
    build:
      <<: *web_build
    command: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"] #config 以下に書いた、設定ファイルを読み込んで起動
    volumes:
      - .:/docker_practice
    depends_on:
      - db
      - redis
volumes:
  db-data:
